#!/usr/bin/env bash
#Transfer a file to my server

FILE_PATH=$1
SERVER_IP=$2
USERNAME=$3
PRIVATE_KEY=$4

if [[ $# -lt 4 ]]; then
    scp -o StrictHostKeyChecking=no "$FILE_PATH" "$USERNAME@$SERVER_IP:~/"
elif [[ $# -lt 3 ]]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -i "$PRIVATE_KEY" -o StrictHostKeyChecking=no "$FILE_PATH" "$USERNAME@$SERVER_IP:~/"
fi
