#!/usr/bin/env bash
# Configure Nginx server to have a custom 404

apt-get -y update

apt-get -y upgrade

apt-get -y install nginx

cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

if [ ! -d /var/www/html ]; then
    sudo mkdir -p /var/www/html
fi

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404error.html

replacement="    error_page 404 /404error.html;\n\tlocation = /404error.html {\n\tinternal;\n\t}\n"

if ! grep -q "error_page 404" /etc/nginx/sites-available/default; then
    sed -i "/^\s*server\s*{[^}]*$/a $replacement" /etc/nginx/sites-available/default
fi

service nginx restart
