#!/usr/bin/env bash
# Prints FizzBuzz for multiples of 3 and 5, Fizz for multiple of 3
# And Buzz for multiple of 5

count=1
while [ $count -le 100 ]; do
   if [ $((count % 3)) -eq 0 ] && [ $((count % 5)) -eq 0 ]; then
       echo "FizzBuzz"
   elif [ $((count % 5)) -eq 0 ]; then
       echo "Buzz"
   elif [ $((count % 3)) -eq 0 ]; then
       echo "Fizz"
   else
      echo "$count"
   fi
   count=$((count + 1))
done
