#!/usr/bin/env bash
# List all content of the current directory using for loop
# List content names after first -

directory="."
for file in "$directory"/*; do
    if [[ ! "$(basename "$file")" == .* ]] && [ -f "$file" ]; then
        filename=$(basename "$file" | cut -d'-' -f2-)
        echo "$filename"
    fi
done
