#!/usr/bin/env bash
apt-get update
apt-get upgrade -y

apt-get install ufw -y

ufw allow 22/tcp
ufw allow 443/tcp
ufw allow 80/tcp

ufw default deny incoming
ufw default allow outgoing

ufw enable

ufw status
